### ISSUE TITLE
Improved search and retrieval of lists #18

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/species-lists#10]
Improved search and retrieval of lists
 Advanced search on lists - Faceting to be improved - searching within and across lists

**Comment by TaniaGLaity** [comment]
no advanced search functionality or filters for ALL lists  - ie can search within a list using filters but not across all lists

**Comment by djtfmartin** [comment]
![Image](https://github.com/AtlasOfLivingAustralia/species-lists/assets/444897/44083a4a-77b0-413c-9e72-adea5c2bd5cc)
![Image](https://github.com/AtlasOfLivingAustralia/species-lists/assets/444897/20bcf8ba-f4dc-4c39-9153-6b3ba7f19edd)
