### ISSUE TITLE
User feedback in the tool  #19

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/species-lists#11]
User feedback in the tool e.g. acknowledgement that a list has been loaded successfully / saved etc

**Comment by TaniaGLaity** [comment]
seems to be working well - but will need to be reviewed on a case by case basis.
e.g. when uploading a list and it fails - not enough detail to rectify issue e.g. 

Missing required fields for list type
The uploaded file has the following validation errors:
Sensitive lists require a generalisation value

I retried and added a generalisation value but it still failed and returned the same error

**Comment by djtfmartin** [comment]
The validation for sensitive lists was checking for 2 columns -  “generalisation” and “category”, but the error message was only reporting “generalisation”.  ive changed it to only check for “generalisation”. i dont think category (at the taxon level) is used by SDS
