### ISSUE TITLE
Ability to create a new list #51

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/species-lists#25]
Ability to create a new list ("Upload a list" - either by loading csv file or pasting a list)

**Comment by TaniaGLaity** [comment]
uploaded a list but got the following error despite the file having a scientific name field - 

CSV Missing required taxonomic fields
The uploaded file has the following validation errors:
Some of the supplied records are missing a scientific name, a taxonID or taxonConceptID. Please add this field to your CSV and try again.

**Comment by djtfmartin** [comment]
thanks @TaniaGLaity. Can you retest this ? Ive tested with the 2 lists you where using and they load ok.

**Comment by TaniaGLaity** [comment]
all good now
