### ISSUE TITLE
List validation - Ability to check list data prior to loading #52

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/species-lists#28]
Ability to check list data prior to loading

**Comment by djtfmartin** [comment]
Basic validation added for 3 list types

<img width="1285" alt="Screenshot 2023-09-21 at 4 36 27 pm" src="https://github.com/AtlasOfLivingAustralia/species-lists/assets/444897/4f37c8fc-fea8-4f77-86ff-905d22083b2f">
<img width="1303" alt="Screenshot 2023-09-21 at 4 36 04 pm" src="https://github.com/AtlasOfLivingAustralia/species-lists/assets/444897/5bfb83be-d80c-4d69-ba7b-b6b30f47f7cf">

**Comment by TaniaGLaity** [comment]
this was about cross-checking that all records have "loaded" correctly prior to them being loaded into system - e.g. contains the right number of rows and columns?

**Comment by djtfmartin** [comment]
Does the line count, and list of recognised fields displayed suffice ?

**Comment by TaniaGLaity** [comment]
oh it probably does - didn't see that when I tested...
