### ISSUE TITLE
Ability to download an existing public list #59

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/species-lists#34]
Ability to download an existing public list

**Comment by djtfmartin** [comment]
Duplicate of #16

**Comment by djtfmartin** [comment]
Basic download accessible on species list view



![Image](https://github.com/AtlasOfLivingAustralia/species-lists/assets/444897/5665da18-febf-4c07-86b0-0d9f1c20ed30)

**Comment by TaniaGLaity** [comment]
works - but question is - should it include the ALA taxonomy columns too?  might be a question for Cam too?

**Comment by djtfmartin** [comment]
Classification columns added.
