### ISSUE TITLE
Be able to filter ("refine") while searching within a list #63

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/species-lists#38]
Be able to filter ("refine") while searching

**Comment by djtfmartin** [comment]
Done at the species list level.

**Comment by TaniaGLaity** [comment]
would be good to be able to do this at the list of lists level

**Comment by djtfmartin** [comment]
Added at lists level



![Image](https://github.com/AtlasOfLivingAustralia/species-lists/assets/444897/93d83d4d-bd15-480d-9b65-be70cd39c38e)
![Image](https://github.com/AtlasOfLivingAustralia/species-lists/assets/444897/55f9e186-6287-487e-8280-23d015e724c6)
