### ISSUE TITLE
Ability to browse for a list #64

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/species-lists#39]
Ability to browse for a list

**Comment by TaniaGLaity** [comment]
at the moment a user can only view 13 lists at a time.  can we enable users to show more than 13 (similar to the current lists tool)
no indication of how many lists there are available.
would be able to sort by list name or filter by list type etc

**Comment by djtfmartin** [comment]
Changes here:

![Image](https://github.com/AtlasOfLivingAustralia/species-lists/assets/444897/aa2c76f9-8b8a-4967-931e-5f9a9c6d8972)
