### ISSUE TITLE
Ability to reload a list #66

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/species-lists#42]
Ability to reload a list

**Comment by TaniaGLaity** [comment]
still not working - getting this error despite adding a generalisation column for the New Zealand Sensitive Species List for Vascular Plants list

The uploaded file has the following validation errors:
Sensitive lists require a generalisation column

**Comment by djtfmartin** [comment]
The validation for sensitive lists was checking for 2 columns -  “generalisation” and “category”, but the error message was only reporting “generalisation”

i've changed it to only check for “generalisation” - i don't think category is used by SDS from the list
