### ISSUE TITLE
Ability to add or remove columns from a list #75

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/species-lists#52]
Ability to add or remove columns from a list

**Comment by djtfmartin** [comment]
This is accessible in the "Danger zone" section. Users can add, remove and rename columns


![Image](https://github.com/AtlasOfLivingAustralia/species-lists/assets/444897/e4f25619-c5ce-4dcb-910a-9fbedff4a285)

**Comment by TaniaGLaity** [comment]
works - need feedback however that a new field has been added / add it to the list of fields to rename / delete

**Comment by djtfmartin** [comment]
I've added some notifications to hopefully make it clearer to the user.



![Image](https://github.com/AtlasOfLivingAustralia/species-lists/assets/444897/ffb483fe-267d-4d58-8227-25ff4eaa3f66)
