### ISSUE TITLE
When creating a new species list the region is missing common items

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/species-lists#70]
When creating a new list the region field is mandatory, limited and difficult to search.

Task
- Make the region field more flexible with an autocomplete mechanism.

Suggestion
- Make the region field an autocomplete with support for both a selected item and free text.
- Add "World" option.
- Add delineation between groups of regions; Countries, States & Territories, External Territories.
- Use sorting within these groups.
- Support queries to `https://spatial.ala.org.au/ws/search?q=`, with an include filter for specific contextual layers e.g. Countries, States and Territories, CAPAD, IMCRA, IBRA, LGA, Gazetteer.

**Comment by TaniaGLaity** [comment]
agree add world
not sure about what regions to include however, this may be a job for the UX/UI project to further define - currently regions in contextual layers is way too complex and unwieldy.

**Comment by jack-brinkman** [comment]
Fixed in #93
