### ISSUE TITLE
Missing server side validation on listType

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/species-lists#82]
I can only find client side validation on list type. There should be something on the server side as well. https://github.com/AtlasOfLivingAustralia/species-lists/blob/develop/lists-ui/src/listTypes.json

**Comment by adam-collins** [comment]
Add a service to get this list. It is a mandatory field in list creation so the list should be public. 

Also, spatial-hub would benefit from a dynamic list.

**Comment by adam-collins** [comment]
There are other mandatory fields; licence, region. Maybe this new REST service should bundle all the valid values given that the UI restricts them.

Task
- Server side validation for metadata fields that are limited by the UI.
- REST/graphql service to retrieve these limited values.

**Comment by jack-brinkman** [comment]
Fixed in #93
