### ISSUE TITLE
Cannot login with a different account

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/species-lists#87]
This has to do with how the cognito login page is not logged by clicking logout in lists. This is a 1hr timeout on the cognito login page that needs resetting. I thought I saw a logout URL in the .env file, not sure if it is related.

To reproduce
- In an empty session (no cookies for lists or cognito's login page), login via lists UI.
- In lists UI click logout.
- In lists UI click login. 
- You are immediately logged in with the previous account. This means you cannot change the account.

Task
- Clicking logout will also log you out of the cognito page.

**Comment by nickdos** [comment]
@adam-collins could you please test this (again) on https://lists-develop.dev.ala.org.au/ - no rush.
